### ISSUE TITLE
Compilation error on 32bit Linux using Gcc-4.8.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gdslang/gdsl-toolkit#2]
```
The toolkit does not compile on a 32bit Linux using Gcc-4.8.2. The following 
compiler error is produced:

./libs/rreil-sim/src/simulator/ops.c:133:1: error: unknown type name
'__uint128_t'
```

Original issue reported on code.google.com by `juliankranz@gmail.com` on 24 Oct 2013 at 1:16
